### ISSUE TITLE
Subclass SASSCompiler instead of CompilerBase

### ISSUE THREAD

**Issue by coilysiren** [sonic182/libsasscompiler#3]
Currently `LibSassCompiler` [(src)](https://github.com/sonic182/libsasscompiler/blob/master/libsasscompiler/__init__.py) repeats a lot of the code in `SASSCompiler ` [(src)](https://github.com/jazzband/django-pipeline/blob/master/pipeline/compilers/sass.py).

A more efficient implementation would subclass `SASSCompiler` and define a `execute_command` that calls `sass.compile`

**Comment by sonic182** [comment]
Hi, PR are welcome :). You could do it and check it with tests easily. if not then I will do it whenever I got time.

**Comment by sonic182** [comment]
Also, it is code that will be executed once in production (and any time you refresh a page in development, but is so fast that it is not important. see related https://github.com/sonic182/libsasscompiler/issues/1)
