### ISSUE TITLE
Support for newer django-pipeline?

### ISSUE THREAD

**Issue by WhyNotHugo** [sonic182/libsasscompiler#5]
Currently, libsasscompiler depends on `django-pipeline (<=1.7.0)`, which is rather old.

I'm wondering what's broken for ~2.0.4? I'm trying to install it, but it seems I've fallen into unsolvable dependency issues:

```
[SolverProblemError]
Because libsasscompiler (0.1.5) depends on django-pipeline (<=1.7.0)
 and no versions of libsasscompiler match >0.1.5,<0.2.0, libsasscompiler (>=0.1.5,<0.2.0) requires django-pipeline (<=1.7.0).
So, because idf depends on both django-pipeline (^2.0.4) and libsasscompiler (^0.1.5), version solving failed.
```

**Comment by sonic182** [comment]
Ok, so new release of django-pipeline and libsass, I'll do a new release hope it in a few hours

**Comment by WhyNotHugo** [comment]
Oh, that'd be great, thanks! :)

**Comment by sonic182** [comment]
Done in https://github.com/sonic182/libsasscompiler/commit/adbd14e1eb17d64eec27ec85cc30e0d806431881

you could try libsasscompile>=0.1.7 now

**Comment by WhyNotHugo** [comment]
Thanks! :slightly_smiling_face:
